name: zi2zi-jit
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - setuptools<81
  - numpy=1.22
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu121
    - torch==2.5.1
    - torchvision==0.20.1
    - opencv-python==4.11.0.86
    - timm==0.9.12
    - tensorboard==2.10.0
    - scipy==1.9.1
    - einops==0.8.1
    - gdown==5.2.0
    - fonttools
    - Pillow<12
    - pytorch-msssim
    - lpips
    - tqdm
    - matplotlib
    - gradio==5.21.0
    - pydantic<2.11
    - pandas<2.3
    - psutil
    - nvidia-ml-py
    - vtracer==0.6.15
    - pytest
    - -e git+https://github.com/LTH14/torch-fidelity.git@master#egg=torch-fidelity
